name: codeshastra
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  timelines: ^0.1.0
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^9.0.0
  speech_to_text: ^6.6.1
  google_translate: ^0.0.6
  flutter_dotenv: ^5.1.0
  google_gemini: ^0.1.2
  flutter_tts: ^4.0.2
  get: 4.6.6
  animated_bottom_navigation_bar: ^1.3.3
  flutter: 
    sdk: flutter
  table_calendar: ^3.0.0
  intl: ^0.17.0

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter



flutter: 
  assets: 
    - .env
  uses-material-design: true

