name: codeshastra
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  timelines: ^0.1.0
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^9.0.0
  get: 4.6.6
  timelines: ^0.1.0
  animated_bottom_navigation_bar: ^1.3.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

