import 'package:get/get.dart';
class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'January': 'January',
          'February': 'February',
          'March': 'March',
          'April': 'April',
          'May': 'May',
          'June': 'June',
          'July': 'July',
          'August': 'August',
          'September': 'September',
          'October': 'October',
          'November': 'November',
          'December': 'December',
          'Hello': 'Hello World',
          'Khetiseva': 'khetiSeva',
          'Add To Cart': 'Add to Cart',
          'Save for later': 'Save for Later',
          'Buy': 'Buy',
          'Sell': 'Sell',
          'PrePlanning': 'PrePlanning',
          'Planting': 'Planting',
          'Sale view': 'Sale View',
        },
        'hi_IN': {
          'January': 'जनवरी',
          'February': 'फरवरी',
          'March': 'मार्च',
          'April': 'अप्रैल',
          'May': 'मई',
          'June': 'जून',
          'July': 'जुलाई',
          'August': 'अगस्त',
          'September': 'सितंबर',
          'October': 'अक्टूबर',
          'November': 'नवंबर',
          'December': 'दिसंबर',
          'Hello': 'नमस्ते दुनिया',
          'Khetiseva': 'खेतीसेवा',
          'Add To Cart': 'कार्ट में जोड़ें',
          'Save for later': 'बाद में सहेजें',
          'Buy': 'खरीदें',
          'Sell': 'बेचें',
          'PrePlanning': 'पूर्व योजना',
          'Planting': 'रोपन',
          'Sale view': 'बिक्री देखें',
        },
        'gu_IN': {
          'January': 'જાન્યુઆરી',
          'February': 'ફેબ્રુઆરી',
          'March': 'માર્ચ',
          'April': 'એપ્રિલ',
          'May': 'મે',
          'June': 'જૂન',
          'July': 'જુલાઈ',
          'August': 'ઓગસ્ટ',
          'September': 'સપ્ટેમ્બર',
          'October': 'ઑક્ટોબર',
          'November': 'નવેમ્બર',
          'December': 'ડિસેમ્બર',
          'Hello': 'હેલો વર્લ્ડ',
          'Khetiseva': 'ખેતીસેવા',
          'Add To Cart': 'કાર્ટમાં ઉમેરો',
          'Save for later': 'પછી માટે સાચવો',
          'Buy': 'ખરીદો',
          'Sell': 'વેચો',
          'PrePlanning': 'પૂર્વ રચના',
          'Planting': 'રોપણ',
          'Sale view': 'વેચાણ જોવો',
        },
        'mr_IN': {
          'January': 'जानेवारी',
          'February': 'फेब्रुवारी',
          'March': 'मार्च',
          'April': 'एप्रिल',
          'May': 'मे',
          'June': 'जून',
          'July': 'जुलै',
          'August': 'ऑगस्ट',
          'September': 'सप्टेंबर',
          'October': 'ऑक्टोबर',
          'November': 'नोव्हेंबर',
          'December': 'डिसेंबर',
          'Hello': 'हॅलो वर्ल्ड',
          'Khetiseva': 'खेतीसेवा',
          'Add To Cart': 'कार्टमध्ये जोडा',
          'Save for later': 'नंतर साठवा',
          'Buy': 'विका',
          'Sell': 'विकणे',
          'PrePlanning': 'पूर्व योजना',
          'Planting': 'रोपण',
          'Sale view': 'विक्री पहा',
        },
        'ta_IN': {
          'January': 'ஜனவரி',
          'February': 'பிப்ரவரி',
          'March': 'மார்ச்',
          'April': 'ஏப்ரல்',
          'May': 'மே',
          'June': 'ஜூன்',
          'July': 'ஜூலை',
          'August': 'ஆகஸ்ட்',
          'September': 'செப்டம்பர்',
          'October': 'அக்டோபர்',
          'November': 'நவம்பர்',
          'December': 'டிசம்பர்',
          'Hello': 'வணக்கம் உலகம்',
          'Khetiseva': 'விவசாயசேவை',
          'Add To Cart': 'கார்ட்டுக்கு சேர்',
          'Save for later': 'பிறகுக்கு சேமி',
          'Buy': 'வாங்கு',
          'Sell': 'விற்க',
          'PrePlanning': 'முன்னோடி திட்டம்',
          'Planting': 'வளர்ப்பு',
          'Sale view': 'விற்பனை பார்க்க',
        },
        'as_IN': {
          'January': 'জানুৱাৰী',
          'February': 'ফেব্ৰুৱাৰী',
          'March': 'মাৰ্চ',
          'April': 'এপ্ৰিল',
          'May': 'মে',
          'June': 'জুন',
          'July': 'জুলাই',
          'August': 'আগষ্ট',
          'September': 'ছেপ্টেম্বৰ',
          'October': 'অক্টোবৰ',
          'November': 'নৱেম্বৰ',
          'December': 'ডিচেম্বৰ',
          'Hello': 'নমস্কাৰ বিশ্ব',
          'Khetiseva': 'খেতি সেৱা',
          'Add To Cart': 'কাৰ্টত যোগ কৰক',
          'Save for later': 'পাছত বাচনি কৰক',
          'Buy': 'ক্ৰয় কৰক',
          'Sell': 'বিক্ৰয় কৰক',
          'PrePlanning': 'প্ৰাথমিক পৰিকল্পনা',
          'Planting': 'বিতৰণ',
          'Sale view': 'বিক্ৰি চাওক',
        },
        'ml_IN': {
          'January': 'ജനുവരി',
          'February': 'ഫെബ്രുവരി',
          'March': 'മാർച്ച്',
          'April': 'ഏപ്രിൽ',
          'May': 'മേയ്',
          'June': 'ജൂൺ',
          'July': 'ജൂലൈ',
          'August': 'ഓഗസ്റ്റ്',
          'September': 'സെപ്റ്റംബർ',
          'October': 'ഒക്‌ടോബർ',
          'November': 'നവംബർ',
          'December': 'ഡിസംബർ',
          'Hello': 'ഹലോ ലോകം',
          'Khetiseva': 'കൃഷി സേവനം',
          'Add To Cart': 'കാർട്ടിലേക്ക് ചേർക്കുക',
          'Save for later': 'ശേഷം സേവ് ചെയ്യുക',
          'Buy': 'വാങ്ങുക',
          'Sell': 'വിൽക്കുക',
          'PrePlanning': 'പ്രീ പ്ലാനിംഗ്',
          'Planting': 'സസ്യവിവക്ഷ',
          'Sale view': 'വിൽപ്പന കാണുക',
        },
        'pa_IN': {
          'January': 'ਜਨਵਰੀ',
          'February': 'ਫਰਵਰੀ',
          'March': 'ਮਾਰਚ',
          'April': 'ਅਪ੍ਰੈਲ',
          'May': 'ਮਈ',
          'June': 'ਜੂਨ',
          'July': 'ਜੁਲਾਈ',
          'August': 'ਅਗਸਤ',
          'September': 'ਸਤੰਬਰ',
          'October': 'ਅਕਤੂਬਰ',
          'November': 'ਨਵੰਬਰ',
          'December': 'ਦਸੰਬਰ',
          'Hello': 'ਹੈਲੋ ਵਰਲਡ',
          'Khetiseva': 'ਖੇਤੀ ਸੇਵਾ',
          'Add To Cart': 'ਕਾਰਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ',
          'Save for later': 'ਬਾਅਦ ਲਈ ਸੰਭਾਲੋ',
          'Buy': 'ਖਰੀਦੋ',
          'Sell': 'ਵੇਚੋ',
          'PrePlanning': 'ਪੂਰਵ-ਯੋਜਨਾ',
          'Planting': 'ਬੋਨਾ',
          'Sale view': 'ਵਿਕਰੀ ਵੇਖੋ',
        },
      };
}

